steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-petclinic:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-petclinic:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/spring-petclinic:$COMMIT_SHA'
